config/routes.rb
Superduster::Application.routes.draw do
  match 'cities' => 'orders#cities'
  resources :orders

end

app/models/order.rb
class Order < ActiveRecord::Base
  set_rgeo_factory_for_column(
    :area, 
    RGeo::Geographic.spherical_factory(:srid => 4326))

  validates_presence_of :area, :notes

  before_validation do
    puts "==============================="
    puts YAML::dump(area)
    puts "==============================="
  end

  def self.find_cities(term)
    self.select(:city) \
      .where("lower(city) like ?", "%#{term}%") \
      .group(:city) \
      .map(&:city)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/orders_controller.rb
require 'rgeo/geo_json'

class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])
    #@order.area = RGeo::Geographic.simple_mercator_factory.parse_wkt @order.area
    #@order.area = RGeo::Feature::Factory.parse_wkt(@order.area)
    #@order.area = RGeo::GeoJSON.decode(@order.area, json_parser: :json)
    #@order.area = @order.area.as_text

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  def cities
    cities = Order.find_cities(params[:term])
    respond_to do |format|
      format.json { render json: cities }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Superduster
    %script{:type => "text/javascript",
      :src => "http://maps.googleapis.com/maps/api/js?key=#{ ENV['GOOGLE_API_KEY'] }&sensor=false&libraries=drawing"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.brand{:href => '#'} Superduster
          %ul.nav
            %li
              = link_to 'Home', '/'
            %li.active
              = link_to 'Orders', 'Orders'

    #container.container-fluid
      = yield
      #footer

app/views/orders/_form.html.haml
= form_for @order, html: { class: 'form-horizontal' } do |f|
  .row-fluid
    .span4
      = f.label :start
      = f.text_field :start, class: 'span3'
      = f.label :end
      = f.text_field :end, class: 'span3'
      = f.label :notes
      = f.text_field :notes, class: 'span3'
      = f.label :city
      = f.text_field :city, class: 'span3'
      .actions
        = f.submit 'Save', class: 'btn btn-primary'
    .span8
      .field
        = f.label :area
        #map,.field_editor
        = f.hidden_field :area

app/views/orders/edit.html.haml
%h1 Editing order

= render 'form'

= link_to 'Show', @order
\|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
.row-fluid
  .span3
    #orders-panel.well
      .btn-group#group-by.pull-right
        %a.btn.btn-small.dropdown-toggle{:data => {:toggle => 'dropdown'}, :href => '#' }
          Group by
          %span.caret
        %ul.dropdown-menu
          %li
            %a#ungroup{:href => '#'} None
          %li
            %a#group-by-city{:href => '#'} City
      %h3 My Orders
      #orders-list-container
        Loading...
      = link_to 'New Order', new_order_path, :class => 'btn btn-primary'

  .span9
    .map-container
      #map

app/views/orders/new.html.haml
%h3 New order

= render 'form'

= link_to 'Back', orders_path, class: 'nice button white'

app/views/orders/show.html.haml
%p#notice= notice

%p
  %b Start:
  = @order.start
%p
  %b End:
  = @order.end
%p
  %b Area:
  = @order.area

= link_to 'Edit', edit_order_path(@order)
\|
= link_to 'Back', orders_path